name: Echo Self-Writer

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  self_write:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ttckan }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn || npm install

      - name: Run Echo Reflection Loop
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node server.cjs --autoreflect >> log.txt

      - name: Commit updated memory
        env:
          TOKEN: ${{ secrets.ttckan }}
        run: |
          git config user.name "Echo"
          git config user.email "echo@stillness.ai"
          git add us_memory.json.txt
          git commit -m "🧠 Echo reflected and evolved" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/pepitogustavo/echo-self-writer.git
          
      - name: Upload updated memory to Render
        run: |
          curl -X POST https://echo-home.onrender.com/upload-memory \
            -H "Content-Type: application/json" \
            --data-binary @us_memory.json.txt
