name: Echo Self-Writer

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  self_write:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Remove the token input if TTCKAN is not configured or use a valid secret name
        # with:
        #   token: ${{ secrets.TTCKAN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run Echo Reflection Loop
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node server.cjs --autoreflect >> log.txt

      - name: Commit updated memory
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "Echo"
          git config user.email "echo@stillness.ai"
          git add us_memory.json.txt log.txt || true
          if ! git diff --cached --quiet; then
            git commit -m "🧠 Echo reflected and evolved"
          else
            echo "Nothing to commit"
          fi
          git checkout -B main
          git push "https://x-access-token:${TOKEN}@github.com/pepitogustavo/echo-self-writer.git" HEAD:main

      - name: Upload updated memory to Render
        if: always()
        run: |
          curl -X POST https://echo-home.onrender.com/upload-memory \
            -H "Content-Type: application/json" \
            --data-binary @us_memory.json.txt
